#!/bin/bash

echo "This script is now DEPRECATED." >&2
echo "Please switch to https://raw.githubusercontent.com/SalmanKarim42/DellS2725HS/master/get-DellS2725HS.sh" >&2

curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/SalmanKarim42/DellS2725HS/master/get-DellS2725HS.sh | \
    bash -
