#!/bin/bash

# Mock version of /opt/dells2725hs-privileged/scripts/change-hostname

echo "Starting mock version of change-hostname..."

echo "Mock change of hostname succeeded (no changes were applied)"
