#!/bin/bash

# Mock version of /opt/DellS2725HS-privileged/scripts/update
#
# On device, the `DellS2725HS-updater` systemd service would facilitate invoking
# the original script.

echo '======== update-opts ========'

# Output all update-opts for debugging purposes.
if [[ -d /home/DellS2725HS/update-opts ]]; then
  for file in /home/DellS2725HS/update-opts/*; do
    echo "${file}: $(cat "${file}")"
  done
else
  echo 'No update opts!'
fi

echo '============================='
