#!/bin/bash

# Mock version of /opt/dells2725hs-privileged/scripts/update
#
# On device, the `dells2725hs-updater` systemd service would facilitate invoking
# the original script.

echo '======== update-opts ========'

# Output all update-opts for debugging purposes.
if [[ -d /home/dells2725hs/update-opts ]]; then
  for file in /home/dells2725hs/update-opts/*; do
    echo "${file}: $(cat "${file}")"
  done
else
  echo 'No update opts!'
fi

echo '============================='
