#!/bin/bash

# Installs DELL_S2725HS and all dependencies.

# Exit on first error.
set -e

# Exit on unset variable.
set -u

# Echo commands before executing them, by default to stderr.
set -x

# Abort installation if the read-only filesystem is enabled.
if grep -q "boot=overlay" /proc/cmdline ; then
  echo 'The read-only filesystem is enabled.' >&2
  echo 'Disable the read-only filesystem before proceeding.' >&2
  exit 1
fi

# Check if the user is forcing an install.
if [[ -n "${FORCE_INSTALL+x}" ]]; then
  echo 'Forcing installation on unsupported setup.'
else
  # Restrict installation to only specific configurations.

  # Install only on Raspberry Pi 4 Model B.
  if ! grep --quiet "^Model\s*: Raspberry Pi 4 Model B" /proc/cpuinfo ; then
    echo 'You are trying to install on unsupported hardware.' >&2
    exit 1
  fi

  # Prevent installation on 64-bit operating systems.
  # Note: the distro ID is called "Raspbian" because the 32-bit version of the
  # Raspberry Pi operating system is based on Raspbian repos (an independent
  # open-source project). Similarly, the the 64-bit version of the Raspberry Pi
  # operating system is based on Debian and its distro ID would be "Debian".
  if [[ "$(lsb_release --id --short)" != 'Raspbian' ]]; then
    echo "DELL_S2725HS currently only supports the 32-bit version of Raspberry Pi OS 11 \"Bullseye\"." >&2
    echo "To install DELL_S2725HS, you'll need Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
    exit 1
  fi

  # Prevent installation on OS versions lower than Raspberry Pi OS 11 "Bullseye".
  if (( "$(lsb_release --release --short)" < 11 )); then
    echo "DELL_S2725HS no longer supports Raspberry Pi OS 10 \"Buster\" or lower." >&2
    echo "To install DELL_S2725HS, you'll need to upgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
    exit 1
  fi

  # Prevent installation on Raspberry Pi OS 12 "Bookworm".
  if (( "$(lsb_release --release --short)" > 11 )); then
    echo "DELL_S2725HS is not yet compatible with Raspberry Pi OS 12 \"Bookworm\"." >&2
    echo "You can track our progress by visiting" >&2
    echo "To install DELL_S2725HS, you'll need to downgrade your operating system to Raspberry Pi OS 11 \"Bullseye\" (32-bit)." >&2
    exit 1
  fi
fi

# Get the filename of the Janus Debian package.
JANUS_DEBIAN_PACKAGE="$(ls janus*.deb)"
readonly JANUS_DEBIAN_PACKAGE

# Get the filename of the uStreamer Debian package.
USTREAMER_DEBIAN_PACKAGE="$(ls ustreamer*.deb)"
readonly USTREAMER_DEBIAN_PACKAGE

# Get the filename of the DELL_S2725HS Debian package.
DELLS2725HS_DEBIAN_PACKAGE="$(ls DellS2725HS*.deb)"
readonly DELLS2725HS_DEBIAN_PACKAGE

# Update apt package index files, allowing the apt repos to change suite name.
apt-get update --allow-releaseinfo-change-suite

apt-get install -y \
  "./${JANUS_DEBIAN_PACKAGE}" \
  "./${USTREAMER_DEBIAN_PACKAGE}" \
  "./${DELLS2725HS_DEBIAN_PACKAGE}"

# Install yq.
mv yq /usr/bin/yq
chmod 0755 /usr/bin/yq
