#!/bin/bash
#
# Installs the local directory's version of DELL_S2725HS's code onto the current
# system.
#
# This script is only for development. DELL_S2725HS Community users should use the
# get-dells2725hs.sh script in the directory root. DELL_S2725HS Pro users should use
# get-dells2725hs-pro.sh from the licensed URL.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u


# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

./dev-scripts/build-debian-pkg --build-targets 'linux/arm/v7'

# Shellcheck recommends find instead of ls for non-alphanumeric filenames, but
# we don't expect non-alphanumeric filenames, and the find equivalent is more
# complex.
# shellcheck disable=SC2012
LATEST_DEBIAN_PACKAGE="${PWD}/$(ls -t debian-pkg/releases/dells2725hs*.deb | head -n 1)"
readonly LATEST_DEBIAN_PACKAGE

# Clear any previous DELL_S2725HS Debian packages in the bundle directory.
find ./bundler/bundle/ -name 'dells2725hs*.deb' -delete

mv "${LATEST_DEBIAN_PACKAGE}" ./bundler/bundle/

./bundler/create-bundle

# Shellcheck recommends find instead of ls for non-alphanumeric filenames, but
# we don't expect non-alphanumeric filenames, and the find equivalent is more
# complex.
# shellcheck disable=SC2012
LATEST_INSTALL_BUNDLE="${PWD}/$(ls -t bundler/dist/dells2725hs*.tgz | head -n 1)"
readonly LATEST_INSTALL_BUNDLE

sudo ./dev-scripts/device/install-bundle "${LATEST_INSTALL_BUNDLE}"
