#!/bin/bash

# Echo commands before executing them, by default to stderr.
set -x

# Treat undefined environment variables as errors.
set -u

# Exit on first error.
set -e

curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/Dell-S2725HS/DellS2725HS/master/get-DellS2725HS.sh | \
    bash -
