#!/bin/bash

# Echo commands before executing them, by default to stderr.
set -x

# Treat undefined environment variables as errors.
set -u

# Exit on first error.
set -e

curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/SalmanKarim42/DellS2725HS/refs/heads/master/get-DellS2725HS.sh?token=GHSAT0AAAAAADEQNCELLANWVX2J4BTLQW6I2B4I7DQ | \
    bash -
