#!/bin/bash
#
# The canonical way to dump logs is through the script below,
# but this file is here for backwards compatibility.
#
# Without this file, we have no way of giving users a dump logs command
# that will work regardless of DELL_S2725HS version.

sudo /opt/DellS2725HS-privileged/scripts/collect-debug-logs
