#!/bin/bash
#
# Starts the backend server in development mode.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Serve DELL_S2725HS in dev mode.
HOST=0.0.0.0 \
  PORT=${PORT:=8000} \
  DEBUG=1 \
  USE_RELOADER=1 \
  APP_SETTINGS_FILE=../dev_app_settings.cfg \
  DELLS2725HS_HOME_DIR="${DELLS2725HS_HOME_DIR:-$(realpath ~)}" \
  ./app/main.py
